api/Empresas_MVC/Models/EmpresaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Empresas_MVC.Models
{
    public class EmpresaViewModel
    {
        //Atributos
        int _empresaID;
        string _nombre;
        string _correo;
        string _direccion;
        string _postal;

        //Propiedades Getters and Setters
        [Key]
        public int EmpresaID { get => _empresaID; set => _empresaID = value; }
        public string Nombre { get => _nombre; set => _nombre = value; }
        public string Correo { get => _correo; set => _correo = value; }
        public string Direccion { get => _direccion; set => _direccion = value; }
        public string Postal { get => _postal; set => _postal = value; }
    }
}

api/Empresas_MVC/Models/ErrorViewModel.cs
using System;

namespace Empresas_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

api/Empresas_MVC/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Empresas_MVC.Models;

namespace Empresas_MVC.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly Empresas_MVCContext _context;

        public EmpresaController(Empresas_MVCContext context)
        {
            _context = context;
        }

        // GET: Empresa
        public async Task<IActionResult> Index()
        {
            return View(await _context.empresa.ToListAsync());
        }

        // GET: Empresa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresaViewModel = await _context.empresa
                .FirstOrDefaultAsync(m => m.EmpresaID == id);
            if (empresaViewModel == null)
            {
                return NotFound();
            }

            return View(empresaViewModel);
        }

        // GET: Empresa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empresa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpresaID,Nombre,Correo,Direccion,Postal")] EmpresaViewModel empresaViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empresaViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empresaViewModel);
        }

        // GET: Empresa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresaViewModel = await _context.empresa.FindAsync(id);
            if (empresaViewModel == null)
            {
                return NotFound();
            }
            return View(empresaViewModel);
        }

        // POST: Empresa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmpresaID,Nombre,Correo,Direccion,Postal")] EmpresaViewModel empresaViewModel)
        {
            if (id != empresaViewModel.EmpresaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empresaViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpresaViewModelExists(empresaViewModel.EmpresaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empresaViewModel);
        }

        // GET: Empresa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresaViewModel = await _context.empresa
                .FirstOrDefaultAsync(m => m.EmpresaID == id);
            if (empresaViewModel == null)
            {
                return NotFound();
            }

            return View(empresaViewModel);
        }

        // POST: Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empresaViewModel = await _context.empresa.FindAsync(id);
            _context.empresa.Remove(empresaViewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpresaViewModelExists(int id)
        {
            return _context.empresa.Any(e => e.EmpresaID == id);
        }
    }
}

api/Empresas_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Empresas_MVC.Models;

namespace Empresas_MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

api/Empresas_MVC/Views/Empresa/Create.cshtml
@model Empresas_MVC.Models.EmpresaViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Crear empresa</h2>

<h4>Información de empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"> <span class="glyphicon glyphicon-user"></span></span>
                    <input asp-for="Nombre" class="form-control" aria-describedby="basic-addon1" required />
                </div>
                <span asp-validation-for="Nombre" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon2">@@</span>
                    <input type="email" asp-for="Correo" class="form-control" aria-describedby="addon2" />
                </div>
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon3"><span class="glyphicon glyphicon-road" ></span></span>
                    <input asp-for="Direccion" class="form-control" aria-describedby="addon3" />
                </div>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postal" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon4">#</span>
                    <input asp-for="Postal" class="form-control" aria-describedby="addon4" />
                </div>
                <span asp-validation-for="Postal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span> Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

api/Empresas_MVC/Views/Empresa/Delete.cshtml
@model Empresas_MVC.Models.EmpresaViewModel

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>

<h3 class="label label-danger"><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span> ¿Seguro que deseas eliminar?</h3>
<div>
    <h4>Empresa: @Html.DisplayTextFor(model => model.Nombre)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Postal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Postal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmpresaID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span> Volver</a>
    </form>
</div>

api/Empresas_MVC/Views/Empresa/Details.cshtml
@model Empresas_MVC.Models.EmpresaViewModel

@{
    ViewData["Title"] = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Empresa: @Html.DisplayTextFor(model => model.Nombre)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Postal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Postal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EmpresaID" class="btn btn-warning">Editar</a> |
    <a asp-action="Index">Volver</a>
</div>

api/Empresas_MVC/Views/Empresa/Edit.cshtml
@model Empresas_MVC.Models.EmpresaViewModel

@{
    ViewData["Title"] = "Editar";
}

<h2>Editar</h2>

<h4>Empresa: @Html.DisplayTextFor(model => model.Nombre)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmpresaID" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"> <span class="glyphicon glyphicon-user"></span></span>
                    <input asp-for="Nombre" class="form-control" aria-describedby="basic-addon1" required />
                </div>
                <span asp-validation-for="Nombre" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon2">@@</span>
                    <input type="email" asp-for="Correo" class="form-control" aria-describedby="addon2" />
                </div>
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon3"><span class="glyphicon glyphicon-road"></span></span>
                    <input asp-for="Direccion" class="form-control" aria-describedby="addon3" />
                </div>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postal" class="control-label"></label>
                <div class="input-group">
                    <span class="input-group-addon" id="addon4">#</span>
                    <input asp-for="Postal" class="form-control" aria-describedby="addon4" />
                </div>
                <span asp-validation-for="Postal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span> Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

api/Empresas_MVC/Views/Empresa/Index.cshtml
@model IEnumerable<Empresas_MVC.Models.EmpresaViewModel>

@{
    ViewData["Title"] = "Empresas";
}

<h2>Empresas</h2>

<p>
    <a asp-action="Create" class="btn btn-primary"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postal)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EmpresaID" title="Editar" class="btn btn-success"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a> |
                <a asp-action="Details" asp-route-id="@item.EmpresaID" title="Detalle" class="btn btn-warning"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a> |
                <a asp-action="Delete" asp-route-id="@item.EmpresaID" title="Eliminar" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
            </td>
        </tr>
}
    </tbody>
</table>

api/Empresas_MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Acerca de";
    ViewData["Message"] = "Esta es un proyecto de estudiante";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

api/Empresas_MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contacto";
    ViewData["Message"] = "Información de contacto" ;
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Radeluis Sanchez<br />
    2018-6577<br />
</address>

<address>
    <strong>Support:</strong> <a href="mailto:20186577@itla.edu.do">20186577@itla.edu.do</a><br />
</address>

api/Empresas_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

api/Empresas_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Empresas_MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Empresa" asp-action="Index" class="navbar-brand">Empresas_MVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Empresa" asp-action="Index">Inicio</a></li>
                    @*<li><a asp-area="" asp-controller="Empresa" asp-action="Index">Empresas</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Empresas_MVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>